# Neuron networks from scratch in Python
References: http://103.203.175.90:81/fdScript/RootOfEBooks/E%20Book%20collection%20-%202024%20-%20G/CSE%20%20IT%20AIDS%20ML/Neural%20Network.pdf

In [1]:
import numpy as np

## Chapter 2: Coding a neuron

### 2.1 A single neuron

In [2]:
#Python
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

def neuron(weights, inputs, bias):
    output = 0
    for w, x in zip(weights, inputs):
        output += w * x
    output += bias
    return output

print(neuron(weights, inputs, bias))

2.3


In [3]:
#Numpy
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

def neuron(weights, inputs, bias):
    return np.dot(weights, inputs) + bias

print(neuron(weights, inputs, bias))

2.3


### 2.2 A layer of neurons

In [4]:
#Python
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

weights_layer = [weights1, weights2, weights3]
bias_layer = [bias1, bias2, bias3]

def layer(inputs, weights_layer, bias_layer):
    output_layer = []
    for weights_neuron, b_i in zip(weights_layer, bias_layer):
        output_neuron = 0
        for w_i, x in zip(weights_neuron, inputs):
            output_neuron += w_i * x
        output_neuron += b_i
        output_layer.append(output_neuron)
    return output_layer

print(layer(inputs, weights_layer, bias_layer))

[4.8, 1.21, 2.385]


In [5]:
#Numpy
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

def layer(weights, biases, inputs):
    return np.dot(weights, inputs) + biases

print(layer(weights, biases, inputs))

[4.8   1.21  2.385]


### 2.3 Tensors, Arrays and Vectors


In [6]:
l = [1,5,6,2]

lol = [[1,5,6,2],
        [3,2,1,3]]

lolol = [[[1,5,6,2],
        [3,2,1,3]],
        [[5,2,1,2],
        [6,4,8,4]],
        [[2,8,5,3],
        [1,1,9,4]]]

### 2.4 Dot Product and Vector Addition

In [7]:
a = [1,2,3]
b = [2,3,4]

def dot_product(a, b):
    output = 0
    for x, y in zip(a, b):
        output += x * y
    return output

print(dot_product(a, b))

20


### 2.5 Batch of Data

### 2.6 Matrix product

In [8]:
a = [[0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10, 11],
     [12, 13, 14, 15]]

b = [[16, 17, 18, 19],
     [20, 21, 22, 23],
     [24, 25, 26, 27],
     [28, 29, 30, 31]]

def dot(a, b):
    output = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            element = 0
            for k in range(len(a[0])):
                element += a[i][k] * b[k][j]
            row.append(element)
        output.append(row)
    return output

print(dot(a, b))


[[152, 158, 164, 170], [504, 526, 548, 570], [856, 894, 932, 970], [1208, 1262, 1316, 1370]]


In [9]:
a = np.arange(16).reshape(4, 4)
b = np.arange(16, 32).reshape(4, 4)

print(np.dot(a, b))

[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


### 2.7 Transposition for the Matrix Product

In [10]:
#Python
a = [[0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10, 11],
     [12, 13, 14, 15]]

def transpose(a):
    output = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            row.append(a[j][i])
        output.append(row)
    return output

print(transpose(a))

[[0, 4, 8, 12], [1, 5, 9, 13], [2, 6, 10, 14], [3, 7, 11, 15]]


In [11]:
#Numpy
a = np.arange(16).reshape(4, 4)
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [12]:
a = [1, 2, 3]
a = np.array(a)
a = np.expand_dims(a, axis=0)
a

array([[1, 2, 3]])

In [13]:
a = [1, 2, 3]
b = [2, 3, 4]
a = np.array([a])
b = np.array([b]).T
np.dot(a, b)

array([[20]])

### 2.8 A Layer of Neurons & Batch of Data

In [14]:
#Python
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
        [0.5, -0.91, 0.26, -0.5],
        [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

def transpose(a):
    output = []
    for i in range(len(a[0])):
        row = []
        for j in range(len(a)):
            row.append(a[j][i])
        output.append(row)
    return output

def dot(a, b):
    output = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            element = 0
            for k in range(len(a[0])):
                element += a[i][k] * b[k][j]
            row.append(element)
        output.append(row)
    return output

def add(a, b):
    output = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            row.append(a[i][j] + b[j])
        output.append(row)
    return output

a = add(dot(inputs, transpose(weights)), biases)
print(a)

[[4.8, 1.21, 2.385], [8.9, -1.8099999999999996, 0.19999999999999996], [1.4100000000000001, 1.0509999999999997, 0.025999999999999912]]


In [15]:
#Numpy
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
        [0.5, -0.91, 0.26, -0.5],
        [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])